/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.telas;

/**
 *
 * @author gabri
 */
public class ValoresIdeais extends javax.swing.JFrame {

    /**
     * Creates new form ValoresIdeais
     */
    public ValoresIdeais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtFosforo = new javax.swing.JLabel();
        rtUnidadeFosforo = new javax.swing.JLabel();
        rtFosforoSolo = new javax.swing.JLabel();
        cxFosforoSolo = new javax.swing.JTextField();
        rtFosforoIdeal = new javax.swing.JLabel();
        cxFosforoIdeal = new javax.swing.JTextField();
        rtFosforoCorrecao = new javax.swing.JLabel();
        cxFosforoCorrecao = new javax.swing.JTextField();
        rtPotassio = new javax.swing.JLabel();
        rtUnidadePotassio = new javax.swing.JLabel();
        rtPotassioSolo = new javax.swing.JLabel();
        cxPotassioSolo = new javax.swing.JTextField();
        rtPotassioIdeal = new javax.swing.JLabel();
        cxPotassioIdeal = new javax.swing.JTextField();
        rtPotassioCorrecao = new javax.swing.JLabel();
        cxPotassioCorrecao = new javax.swing.JTextField();
        rtCalcio = new javax.swing.JLabel();
        rtUnidadeCalcio = new javax.swing.JLabel();
        rtCalcioSolo = new javax.swing.JLabel();
        cxCalcioSolo = new javax.swing.JTextField();
        rtCalcioIdeal = new javax.swing.JLabel();
        cxCalcioIdeal = new javax.swing.JTextField();
        rtCalcioCorrecao = new javax.swing.JLabel();
        cxCalcioCorrecao = new javax.swing.JTextField();
        rtMagnesio = new javax.swing.JLabel();
        rtUnidadeMagnesio = new javax.swing.JLabel();
        rtMagnesioSolo = new javax.swing.JLabel();
        cxMagnesioSolo = new javax.swing.JTextField();
        rtMagnesioIdeal = new javax.swing.JLabel();
        cxMagnesioIdeal = new javax.swing.JTextField();
        rtMagnesioCorrecao = new javax.swing.JLabel();
        cxMagnesioCorrecao = new javax.swing.JTextField();
        rtEnxofre = new javax.swing.JLabel();
        rtUnidadeEnxofre = new javax.swing.JLabel();
        rtEnxofreSolo = new javax.swing.JLabel();
        cxEnxofreSolo = new javax.swing.JTextField();
        rtEnxofreIdeal = new javax.swing.JLabel();
        cxEnxofreideal = new javax.swing.JTextField();
        rtEnxofreCorrecao = new javax.swing.JLabel();
        cxEnxofreCorrecao = new javax.swing.JTextField();
        rtAluminio = new javax.swing.JLabel();
        rtEnxofreSolo1 = new javax.swing.JLabel();
        cxEnxofreSolo1 = new javax.swing.JTextField();
        rtEnxofreIdeal1 = new javax.swing.JLabel();
        cxEnxofreideal1 = new javax.swing.JTextField();
        rtEnxofreCorrecao1 = new javax.swing.JLabel();
        cxEnxofreCorrecao1 = new javax.swing.JTextField();
        rtHAL = new javax.swing.JLabel();
        rtHALSolo = new javax.swing.JLabel();
        cxHALSolo = new javax.swing.JTextField();
        rtHALIdeal = new javax.swing.JLabel();
        cxHALIdeal = new javax.swing.JTextField();
        rtHALCorrecao = new javax.swing.JLabel();
        cxHALCorrecao = new javax.swing.JTextField();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valores Ideais");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        rtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        rtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtTitulo.setText("Valores Ideais");
        rtTitulo.setPreferredSize(new java.awt.Dimension(400, 75));
        getContentPane().add(rtTitulo);
        rtTitulo.setBounds(312, 6, 400, 75);

        rtFosforo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtFosforo.setForeground(new java.awt.Color(0, 0, 0));
        rtFosforo.setText("Fósforo");
        getContentPane().add(rtFosforo);
        rtFosforo.setBounds(120, 87, 64, 25);

        rtUnidadeFosforo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeFosforo.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeFosforo.setText("(mg.dm³)");
        getContentPane().add(rtUnidadeFosforo);
        rtUnidadeFosforo.setBounds(205, 91, 56, 20);

        rtFosforoSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtFosforoSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtFosforoSolo.setText("No solo:");
        getContentPane().add(rtFosforoSolo);
        rtFosforoSolo.setBounds(120, 123, 50, 20);

        cxFosforoSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxFosforoSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxFosforoSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxFosforoSolo);
        cxFosforoSolo.setBounds(205, 118, 150, 30);

        rtFosforoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtFosforoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtFosforoIdeal.setText("Ideal:");
        getContentPane().add(rtFosforoIdeal);
        rtFosforoIdeal.setBounds(373, 123, 32, 20);

        cxFosforoIdeal.setEditable(false);
        cxFosforoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxFosforoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxFosforoIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxFosforoIdeal);
        cxFosforoIdeal.setBounds(423, 118, 150, 30);

        rtFosforoCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtFosforoCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtFosforoCorrecao.setText("Após correções:");
        getContentPane().add(rtFosforoCorrecao);
        rtFosforoCorrecao.setBounds(591, 123, 96, 20);

        cxFosforoCorrecao.setEditable(false);
        cxFosforoCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxFosforoCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxFosforoCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxFosforoCorrecao);
        cxFosforoCorrecao.setBounds(705, 118, 150, 30);

        rtPotassio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtPotassio.setForeground(new java.awt.Color(0, 0, 0));
        rtPotassio.setText("Potássio");
        getContentPane().add(rtPotassio);
        rtPotassio.setBounds(120, 166, 71, 25);

        rtUnidadePotassio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadePotassio.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadePotassio.setText("(cmol)");
        getContentPane().add(rtUnidadePotassio);
        rtUnidadePotassio.setBounds(209, 170, 37, 20);

        rtPotassioSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtPotassioSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtPotassioSolo.setText("No solo:");
        getContentPane().add(rtPotassioSolo);
        rtPotassioSolo.setBounds(120, 202, 50, 20);

        cxPotassioSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxPotassioSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxPotassioSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPotassioSolo);
        cxPotassioSolo.setBounds(205, 197, 150, 30);

        rtPotassioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtPotassioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtPotassioIdeal.setText("Ideal:");
        getContentPane().add(rtPotassioIdeal);
        rtPotassioIdeal.setBounds(373, 202, 32, 20);

        cxPotassioIdeal.setEditable(false);
        cxPotassioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxPotassioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxPotassioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPotassioIdeal);
        cxPotassioIdeal.setBounds(423, 197, 150, 30);

        rtPotassioCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtPotassioCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtPotassioCorrecao.setText("Após correções:");
        getContentPane().add(rtPotassioCorrecao);
        rtPotassioCorrecao.setBounds(591, 202, 96, 20);

        cxPotassioCorrecao.setEditable(false);
        cxPotassioCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxPotassioCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxPotassioCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPotassioCorrecao);
        cxPotassioCorrecao.setBounds(705, 197, 150, 30);

        rtCalcio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtCalcio.setForeground(new java.awt.Color(0, 0, 0));
        rtCalcio.setText("Cálcio");
        getContentPane().add(rtCalcio);
        rtCalcio.setBounds(120, 245, 51, 25);

        rtUnidadeCalcio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeCalcio.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeCalcio.setText("(cmol)");
        getContentPane().add(rtUnidadeCalcio);
        rtUnidadeCalcio.setBounds(209, 249, 37, 20);

        rtCalcioSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtCalcioSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtCalcioSolo.setText("No solo:");
        getContentPane().add(rtCalcioSolo);
        rtCalcioSolo.setBounds(120, 281, 50, 20);

        cxCalcioSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxCalcioSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxCalcioSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxCalcioSolo);
        cxCalcioSolo.setBounds(205, 276, 150, 30);

        rtCalcioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtCalcioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtCalcioIdeal.setText("Ideal:");
        getContentPane().add(rtCalcioIdeal);
        rtCalcioIdeal.setBounds(373, 281, 32, 20);

        cxCalcioIdeal.setEditable(false);
        cxCalcioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxCalcioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxCalcioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxCalcioIdeal);
        cxCalcioIdeal.setBounds(423, 276, 150, 30);

        rtCalcioCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtCalcioCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtCalcioCorrecao.setText("Após correções:");
        getContentPane().add(rtCalcioCorrecao);
        rtCalcioCorrecao.setBounds(591, 281, 96, 20);

        cxCalcioCorrecao.setEditable(false);
        cxCalcioCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxCalcioCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxCalcioCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxCalcioCorrecao);
        cxCalcioCorrecao.setBounds(705, 276, 150, 30);

        rtMagnesio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtMagnesio.setForeground(new java.awt.Color(0, 0, 0));
        rtMagnesio.setText("Magnésio");
        getContentPane().add(rtMagnesio);
        rtMagnesio.setBounds(120, 324, 83, 25);

        rtUnidadeMagnesio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeMagnesio.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeMagnesio.setText("(cmol)");
        getContentPane().add(rtUnidadeMagnesio);
        rtUnidadeMagnesio.setBounds(209, 328, 37, 20);

        rtMagnesioSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtMagnesioSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtMagnesioSolo.setText("No solo:");
        getContentPane().add(rtMagnesioSolo);
        rtMagnesioSolo.setBounds(120, 360, 50, 20);

        cxMagnesioSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxMagnesioSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxMagnesioSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxMagnesioSolo);
        cxMagnesioSolo.setBounds(205, 355, 150, 30);

        rtMagnesioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtMagnesioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtMagnesioIdeal.setText("Ideal:");
        getContentPane().add(rtMagnesioIdeal);
        rtMagnesioIdeal.setBounds(373, 360, 32, 20);

        cxMagnesioIdeal.setEditable(false);
        cxMagnesioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxMagnesioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxMagnesioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxMagnesioIdeal);
        cxMagnesioIdeal.setBounds(423, 355, 150, 30);

        rtMagnesioCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtMagnesioCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtMagnesioCorrecao.setText("Após correções:");
        getContentPane().add(rtMagnesioCorrecao);
        rtMagnesioCorrecao.setBounds(591, 360, 96, 20);

        cxMagnesioCorrecao.setEditable(false);
        cxMagnesioCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxMagnesioCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxMagnesioCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxMagnesioCorrecao);
        cxMagnesioCorrecao.setBounds(705, 355, 150, 30);

        rtEnxofre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtEnxofre.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofre.setText("Enxofre");
        getContentPane().add(rtEnxofre);
        rtEnxofre.setBounds(120, 403, 66, 25);

        rtUnidadeEnxofre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeEnxofre.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeEnxofre.setText("(mg.dm³)");
        getContentPane().add(rtUnidadeEnxofre);
        rtUnidadeEnxofre.setBounds(205, 407, 56, 20);

        rtEnxofreSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtEnxofreSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofreSolo.setText("No solo:");
        getContentPane().add(rtEnxofreSolo);
        rtEnxofreSolo.setBounds(120, 439, 50, 20);

        cxEnxofreSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreSolo);
        cxEnxofreSolo.setBounds(205, 434, 150, 30);

        rtEnxofreIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtEnxofreIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofreIdeal.setText("Ideal:");
        getContentPane().add(rtEnxofreIdeal);
        rtEnxofreIdeal.setBounds(373, 439, 32, 20);

        cxEnxofreideal.setEditable(false);
        cxEnxofreideal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreideal.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreideal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreideal);
        cxEnxofreideal.setBounds(423, 434, 150, 30);

        rtEnxofreCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtEnxofreCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofreCorrecao.setText("Após correções:");
        getContentPane().add(rtEnxofreCorrecao);
        rtEnxofreCorrecao.setBounds(591, 439, 96, 20);

        cxEnxofreCorrecao.setEditable(false);
        cxEnxofreCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreCorrecao);
        cxEnxofreCorrecao.setBounds(705, 434, 150, 30);

        rtAluminio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtAluminio.setForeground(new java.awt.Color(0, 0, 0));
        rtAluminio.setText("Alumínio");
        getContentPane().add(rtAluminio);
        rtAluminio.setBounds(120, 482, 77, 25);

        rtEnxofreSolo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtEnxofreSolo1.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofreSolo1.setText("No solo:");
        getContentPane().add(rtEnxofreSolo1);
        rtEnxofreSolo1.setBounds(120, 518, 50, 20);

        cxEnxofreSolo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreSolo1.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreSolo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreSolo1);
        cxEnxofreSolo1.setBounds(205, 513, 150, 30);

        rtEnxofreIdeal1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtEnxofreIdeal1.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofreIdeal1.setText("Ideal:");
        getContentPane().add(rtEnxofreIdeal1);
        rtEnxofreIdeal1.setBounds(373, 518, 32, 20);

        cxEnxofreideal1.setEditable(false);
        cxEnxofreideal1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreideal1.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreideal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreideal1);
        cxEnxofreideal1.setBounds(423, 513, 150, 30);

        rtEnxofreCorrecao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtEnxofreCorrecao1.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofreCorrecao1.setText("Após correções:");
        getContentPane().add(rtEnxofreCorrecao1);
        rtEnxofreCorrecao1.setBounds(591, 518, 96, 20);

        cxEnxofreCorrecao1.setEditable(false);
        cxEnxofreCorrecao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreCorrecao1.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreCorrecao1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreCorrecao1);
        cxEnxofreCorrecao1.setBounds(705, 513, 150, 30);

        rtHAL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtHAL.setForeground(new java.awt.Color(0, 0, 0));
        rtHAL.setText("H + AL");
        getContentPane().add(rtHAL);
        rtHAL.setBounds(120, 561, 59, 25);

        rtHALSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtHALSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtHALSolo.setText("No solo:");
        getContentPane().add(rtHALSolo);
        rtHALSolo.setBounds(120, 597, 50, 20);

        cxHALSolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxHALSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxHALSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxHALSolo);
        cxHALSolo.setBounds(205, 592, 150, 30);

        rtHALIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtHALIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtHALIdeal.setText("Ideal:");
        getContentPane().add(rtHALIdeal);
        rtHALIdeal.setBounds(373, 597, 32, 20);

        cxHALIdeal.setEditable(false);
        cxHALIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxHALIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxHALIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxHALIdeal);
        cxHALIdeal.setBounds(423, 592, 150, 30);

        rtHALCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtHALCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtHALCorrecao.setText("Após correções:");
        getContentPane().add(rtHALCorrecao);
        rtHALCorrecao.setBounds(591, 597, 96, 20);

        cxHALCorrecao.setEditable(false);
        cxHALCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxHALCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxHALCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxHALCorrecao);
        cxHALCorrecao.setBounds(705, 592, 150, 30);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 2\\Arquitetura de Software\\GUIsoilcorrection\\GUIsoilcorrection\\src\\main\\java\\gui\\imagens\\fundo3.jpg")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(0, 0, 1030, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoresIdeais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxCalcioCorrecao;
    private javax.swing.JTextField cxCalcioIdeal;
    private javax.swing.JTextField cxCalcioSolo;
    private javax.swing.JTextField cxEnxofreCorrecao;
    private javax.swing.JTextField cxEnxofreCorrecao1;
    private javax.swing.JTextField cxEnxofreSolo;
    private javax.swing.JTextField cxEnxofreSolo1;
    private javax.swing.JTextField cxEnxofreideal;
    private javax.swing.JTextField cxEnxofreideal1;
    private javax.swing.JTextField cxFosforoCorrecao;
    private javax.swing.JTextField cxFosforoIdeal;
    private javax.swing.JTextField cxFosforoSolo;
    private javax.swing.JTextField cxHALCorrecao;
    private javax.swing.JTextField cxHALIdeal;
    private javax.swing.JTextField cxHALSolo;
    private javax.swing.JTextField cxMagnesioCorrecao;
    private javax.swing.JTextField cxMagnesioIdeal;
    private javax.swing.JTextField cxMagnesioSolo;
    private javax.swing.JTextField cxPotassioCorrecao;
    private javax.swing.JTextField cxPotassioIdeal;
    private javax.swing.JTextField cxPotassioSolo;
    private javax.swing.JLabel rtAluminio;
    private javax.swing.JLabel rtCalcio;
    private javax.swing.JLabel rtCalcioCorrecao;
    private javax.swing.JLabel rtCalcioIdeal;
    private javax.swing.JLabel rtCalcioSolo;
    private javax.swing.JLabel rtEnxofre;
    private javax.swing.JLabel rtEnxofreCorrecao;
    private javax.swing.JLabel rtEnxofreCorrecao1;
    private javax.swing.JLabel rtEnxofreIdeal;
    private javax.swing.JLabel rtEnxofreIdeal1;
    private javax.swing.JLabel rtEnxofreSolo;
    private javax.swing.JLabel rtEnxofreSolo1;
    private javax.swing.JLabel rtFosforo;
    private javax.swing.JLabel rtFosforoCorrecao;
    private javax.swing.JLabel rtFosforoIdeal;
    private javax.swing.JLabel rtFosforoSolo;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtHAL;
    private javax.swing.JLabel rtHALCorrecao;
    private javax.swing.JLabel rtHALIdeal;
    private javax.swing.JLabel rtHALSolo;
    private javax.swing.JLabel rtMagnesio;
    private javax.swing.JLabel rtMagnesioCorrecao;
    private javax.swing.JLabel rtMagnesioIdeal;
    private javax.swing.JLabel rtMagnesioSolo;
    private javax.swing.JLabel rtPotassio;
    private javax.swing.JLabel rtPotassioCorrecao;
    private javax.swing.JLabel rtPotassioIdeal;
    private javax.swing.JLabel rtPotassioSolo;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtUnidadeCalcio;
    private javax.swing.JLabel rtUnidadeEnxofre;
    private javax.swing.JLabel rtUnidadeFosforo;
    private javax.swing.JLabel rtUnidadeMagnesio;
    private javax.swing.JLabel rtUnidadePotassio;
    // End of variables declaration//GEN-END:variables
}
